import cuid from 'cuid';

const currentDate = new Date();
const currentYear = currentDate.getFullYear();
const currentMonth = currentDate.getMonth();

export default [
  {
    id: cuid(),
    title: 'Test',
    start: new Date(currentYear, currentMonth, 0),
    end: new Date(currentYear, currentMonth, 5),
    visible: true,
    weight: 200,
  },
  {
    id: cuid(),
    title: 'All Day Event',
    allDay: true,
    start: new Date(currentYear, currentMonth, 0),
    end: new Date(currentYear, currentMonth, 1),
    weight: 100,
  },
  {
    id: cuid(),
    title: 'Long Event',
    start: new Date(currentYear, currentMonth, 7),
    end: new Date(currentYear, currentMonth, 10),
    styles: {
      backgroundColor: '#d4d4d4',
      borderColor: 'black',
      borderStyle: 'solid',
      borderWidth: '0',
      color: 'black',
      fontFamily: 'Arial',
      fontSize: '16px',
      fontStyle: 'normal',
      fontWeight: 'bold',
    },
    weight: 200,
  },
  {
    id: cuid(),
    title: 'All Day Event',
    allDay: true,
    start: new Date(currentYear, currentMonth, 7),
    end: new Date(currentYear, currentMonth, 10),
    weight: 200,
  },
  {
    id: cuid(),
    title: 'DTS STARTS',
    start: new Date(2016, 2, 13, 0, 0, 0),
    end: new Date(2016, 2, 20, 0, 0, 0),
    weight: 300,
  },
  {
    id: cuid(),
    title: 'DTS ENDS',
    start: new Date(2016, 10, 6, 0, 0, 0),
    end: new Date(2016, 10, 13, 0, 0, 0),
    weight: 400,
  },
  {
    id: cuid(),
    title: 'Some Event',
    start: new Date(currentYear, currentMonth, 9, 0, 0, 0),
    end: new Date(currentYear, currentMonth, 9, 0, 0, 0),
    weight: 100,
  },
  {
    id: cuid(),
    title: 'Some Event 2',
    start: new Date(currentYear, currentMonth, 9, 0, 0, 0),
    end: new Date(currentYear, currentMonth, 9, 0, 0, 0),
    weight: 200,
  },
  {
    id: cuid(),
    title: 'Conference',
    start: new Date(currentYear, currentMonth, 11),
    end: new Date(currentYear, currentMonth, 13),
    desc: 'Big conference for important people',
    weight: 100,
  },
  {
    id: cuid(),
    title: 'Meeting',
    start: new Date(currentYear, currentMonth, 12, 10, 30, 0, 0),
    end: new Date(currentYear, currentMonth, 12, 12, 30, 0, 0),
    desc: 'Pre-meeting meeting, to prepare for the meeting',
    weight: 200,
  },
  {
    id: cuid(),
    title: 'Lunch',
    start: new Date(currentYear, currentMonth, 12, 12, 0, 0, 0),
    end: new Date(currentYear, currentMonth, 12, 13, 0, 0, 0),
    desc: 'Power lunch',
    weight: 300,
  },
  {
    id: cuid(),
    title: 'Meeting',
    start: new Date(currentYear, currentMonth, 12, 14, 0, 0, 0),
    end: new Date(currentYear, currentMonth, 12, 15, 0, 0, 0),
    weight: 400,
  },
  {
    id: cuid(),
    title: 'Happy Hour',
    start: new Date(currentYear, currentMonth, 12, 17, 0, 0, 0),
    end: new Date(currentYear, currentMonth, 12, 17, 30, 0, 0),
    desc: 'Most important meal of the day',
    weight: 500,
  },
  {
    id: cuid(),
    title: 'Dinner',
    start: new Date(currentYear, currentMonth, 12, 20, 0, 0, 0),
    end: new Date(currentYear, currentMonth, 12, 21, 0, 0, 0),
    weight: 600,
  },
  {
    id: cuid(),
    title: 'Birthday Party',
    start: new Date(currentYear, currentMonth, 13, 7, 0, 0),
    end: new Date(currentYear, currentMonth, 13, 10, 30, 0),
    weight: 1200,
  },
  {
    id: cuid(),
    title: 'Late Night Event',
    start: new Date(currentYear, currentMonth, 17, 19, 30, 0),
    end: new Date(currentYear, currentMonth, 18, 2, 0, 0),
    weight: 1300,
  },
  {
    id: cuid(),
    title: 'Multi-day Event',
    start: new Date(currentYear, currentMonth, 20, 19, 30, 0),
    end: new Date(currentYear, currentMonth, 22, 2, 0, 0),
    weight: 1400,
  },
];
